"""
POST /api/insights — Generate personalised carbon reduction insights.

Primary engine: Google Vertex AI Gemini.
Fallback engine: Deterministic rule-based system (always available).

After generating insights, fires background tasks to:
  - Log anonymised event to BigQuery
  - Publish event to Pub/Sub
"""

import asyncio
import logging
from collections.abc import Coroutine
from typing import Any, Literal, TypedDict, cast

from fastapi import APIRouter, Request

from app.carbon.calculator import get_rule_based_insights
from app.core.config import get_settings
from app.core.rate_limit import INSIGHTS_LIMIT, limiter
from app.models.carbon import CarbonResult
from app.models.insights import InsightItem, InsightsRequest, InsightsResponse
from app.services import bigquery_service, pubsub_service
from app.services.gemini_service import GeminiUnavailableError, generate_insights_gemini

logger = logging.getLogger(__name__)

router = APIRouter(tags=["Insights"])

# Strong references to in-flight background tasks. asyncio only holds a *weak*
# reference to bare create_task() results, so without this set the garbage
# collector can cancel a logging/publish task mid-flight. We discard each task
# from the set once it finishes.
_background_tasks: set[asyncio.Task[Any]] = set()


class AnalyticsPayload(TypedDict):
    """Typed kwargs for `bigquery_service.log_event_async`."""

    total_kg: float
    diet_type: str
    insight_source: str
    top_category: str


def _spawn_background(coro: Coroutine[Any, Any, None]) -> None:
    """Schedule a fire-and-forget coroutine while keeping a strong reference."""
    task = asyncio.create_task(coro)
    _background_tasks.add(task)
    task.add_done_callback(_background_tasks.discard)


def _analytics_payload(result: CarbonResult, source: str, top_category: str) -> AnalyticsPayload:
    """Build the BigQuery event kwargs from a result.

    Pulled out as a pure function so it can be unit-tested: the diet_type must
    come from the echoed input (`result.diet_type`), never from the numeric
    `breakdown` dict (which has no such key).
    """
    return {
        "total_kg": result.total_kg,
        "diet_type": result.diet_type,
        "insight_source": source,
        "top_category": top_category,
    }


@router.post(
    "/insights",
    response_model=InsightsResponse,
    summary="Generate personalised carbon reduction insights",
    description=(
        "Generate 3 personalised, quantified carbon reduction actions. "
        "Uses Gemini (primary) with automatic fallback to the rule-based engine."
    ),
)
@limiter.limit(INSIGHTS_LIMIT)
async def get_insights(request: Request, body: InsightsRequest) -> InsightsResponse:
    """
    Generate personalised carbon reduction insights.

    Rate limited to 10 requests/minute per IP.
    """
    settings = get_settings()
    result = body.carbon_result
    top_category = result.ranked_categories[0].category if result.ranked_categories else "general"
    ranked = [item.model_dump() for item in result.ranked_categories]

    source: str
    raw_insights: list[InsightItem]

    # ------------------------------------------------------------------
    # Try Gemini (primary)
    # ------------------------------------------------------------------
    if settings.USE_GEMINI:
        try:
            raw_insights = await generate_insights_gemini(
                ranked_categories=ranked,
                total_kg=result.total_kg,
            )
            source = "gemini"
            logger.info("Insights generated by Gemini for device %s", body.device_id[:8])
        except GeminiUnavailableError as exc:
            logger.warning("Gemini unavailable, falling back to rules: %s", exc)
            raw_insights = _apply_rule_engine(result, ranked)
            source = "rules"
    else:
        raw_insights = _apply_rule_engine(result, ranked)
        source = "rules"

    # ------------------------------------------------------------------
    # Fire-and-forget background analytics (non-blocking, non-raising)
    # ------------------------------------------------------------------
    if settings.USE_BIGQUERY:
        _spawn_background(
            bigquery_service.log_event_async(**_analytics_payload(result, source, top_category))
        )

    if settings.USE_PUBSUB:
        _spawn_background(
            pubsub_service.publish_insight_request(
                footprint_total=result.total_kg,
                top_category=top_category,
            )
        )

    total_saving = round(sum(i.estimated_saving_kg for i in raw_insights), 1)

    return InsightsResponse(
        insights=raw_insights,
        source=cast(Literal["gemini", "rules"], source),
        total_potential_saving_kg=total_saving,
    )


def _apply_rule_engine(result: CarbonResult, ranked: list[dict[str, Any]]) -> list[InsightItem]:
    """Convert rule engine output dicts to InsightItem instances.

    Uses the lifestyle context echoed onto the result (diet, consumption,
    flights) so the deterministic fallback is just as personalised as the
    Gemini path — a meat-heavy frequent flyer and a vegan non-flyer get
    genuinely different advice. ``ranked`` is the already-serialised ranked
    category list, threaded through from the caller to avoid recomputing it.
    """
    raw_dicts = get_rule_based_insights(
        ranked_categories=ranked,
        breakdown=result.breakdown,
        diet_type=result.diet_type,
        consumption_level=result.consumption_level,
        flights_short_haul=result.flights_short_haul,
        flights_long_haul=result.flights_long_haul,
    )
    return [InsightItem(**d) for d in raw_dicts]
